### PR TITLE
Fix Umlauts in German translation

### PR DESCRIPTION
**Pull request by mruncreative**
Fixed Umlaute in German translation

### CODE REVIEW

**Comment by wsor4035** [comment]
cc @BuckarooBanzay or @Niklp09

**Review by OgelGames — APPROVED** [review]
This was also mentioned in a comment by another user: https://content.minetest.net/threads/8340/

**Review by SwissalpS — APPROVED** [review]

**Comment by wsor4035** [comment]
> This was also mentioned in a comment by another user: https://content.minetest.net/threads/8340/

same person

**Comment by SwissalpS** [comment]
Does what it says in title.

Would be nice if it also fixed line 12:
Verschalteltes -> Verschachteltes

and line 26:
Lichtlevel -> Lichtstärke

**Review by Niklp09 — APPROVED** [review]
Looks good. Please address SwissalpS’ comment from above as well.

**Comment by mruncreative** [comment]
SwissalpS is right. I didn't even read it. Just fixed Umlaute before going to bed. Now that I look at it, it's all horrible broken German and translations are missing. I rewrote it.

**Review by SwissalpS — APPROVED** [review]
Big yes from me. Reads a lot better now, thanks a lot.

**Review by OgelGames — APPROVED** [review]

**Pull request merged**
