### PR TITLE
Add Indonesian translations

### PR DESCRIPTION
**Pull request by srifqi**
This PR adds Indonesian translations.

### CODE REVIEW

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by Niklp09** [comment]
oops sorry, I've overlooked the requested review :confused:

**Comment by BuckarooBanzay** [comment]
> oops sorry, I've overlooked the requested review 😕

no worries, i just remembered that Ogel did some stuff here lately and maybe has some objections/enhancements to this PR, but it could also be done at a later time if even :shrug:

**Comment by OgelGames** [comment]
All good 👍 Nothing to object to when it's just a translation file being added :)

**Comment by srifqi** [comment]
Thank you for the merge!

**Pull request merged**
