### PR TITLE
Technic migrate update

### PR DESCRIPTION
**Pull request by Athozus**
This PR contains commits that occurred on `wrench/` directory of `technic`. Note that the files path were updated automatically during the process (`wrench/init.lua` becomes `init.lua`). However, due to the new commit that occurred after the beginning of the migration, I'm not sure this is will easy as I hope.

### CODE REVIEW

**Comment by Athozus** [comment]
There's might be an huge conflict with 79496a3 :eyes:

**Comment by S-S-X** [comment]
> This PR contains commits that occurred on wrench/ directory of technic

Note also that almost all of these commits are already here and only some of the last are missing but even those might well be irrelevant. Basically this seems to be mostly reapplying, through pulling duplicate commits, old stuff that has been rewritten.
Would be good if you compare individual commits a bit with wrench master branch history and drop irrelevant commits, then there might be some value.

**Comment by Athozus** [comment]
> > This PR contains commits that occurred on wrench/ directory of technic
> 
> Note also that almost all of these commits are already here and only some of the last are missing but even those might well be irrelevant. Basically this seems to be mostly reapplying, through pulling duplicate commits, old stuff that has been rewritten. Would be good if you compare individual commits a bit with wrench master branch history and drop irrelevant commits, then there might be some value.

In fact the problem is that I've made this branch alongside `master` branch without any "link" like a traditional `git branch new-branch`. I think this is why it contains every commits, even if I wanted to get only the new commits like a normal PR. It looks like the 79496a3 commit is in conflict with the root one in `technic-migrate-update` while this same root commit is in `master`. This is a strange situation I've never occurred and I'm wondering how to fix it.

**Comment by S-S-X** [comment]
> This is a strange situation I've never occurred and I'm wondering how to fix it.

First, rebase it so that there's no old commits. That makes it cleaner.

Then pick one:
* see if you can add those translations without conflicts.
* see what actually has been updated on technic repo side.

Also good to know that I did squash some work where commits become incomplete through direct path stripping and dropped unnecessary commits that contained duplicate updates with same commit id (there's now for example my commit d7434f9 which does not belong here, also merge and other).
edit to make it clear: squashed and stripped when I moved commits from technic to here just before that big rewrite.

**Comment by OgelGames** [comment]
As I said in https://github.com/mt-mods/technic/issues/253#issuecomment-1650914554, I am working on this already.

**Pull request closed without merging**
